import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { renderMarkdownToPDFElements } from "./renderMarkdownToPDFElements";

interface MachineMeta {
  Merk?: string;
  Model?: string;
  No_Seri?: string;
  jenis_pesawat?: string;
}

interface QCRow {
  Tanggal_uji?: string;
  [key: string]: unknown;
}

interface AIReportPDFProps {
  markdown: string;
  qcData: QCRow[];
  machine: MachineMeta | null;
  startDate: string;
  endDate: string;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: { marginBottom: 20, borderBottom: "2 solid #059669", paddingBottom: 12 },
  title: { fontSize: 22, fontWeight: "bold", color: "#065f46", marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#6b7280" },
  machineInfo: { fontSize: 10, color: "#374151", marginTop: 6 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", color: "#065f46", marginTop: 20, marginBottom: 10 },
  tableHeader: { backgroundColor: "#d1fae5", fontWeight: "bold", fontSize: 8, padding: 3 },
  tableCell: { fontSize: 8, padding: 3, border: "0.5 solid #d1d5db" },
  tableRow: { flexDirection: "row" },
  table: { marginBottom: 12 },
  footer: { position: "absolute", bottom: 20, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#9ca3af", borderTop: "0.5 solid #e5e7eb", paddingTop: 8 },
  aiBadge: { fontSize: 8, color: "#6b7280", fontStyle: "italic", marginBottom: 8 },
});

function buildQCDataTable(qcData: QCRow[]): React.ReactNode[] {
  if (qcData.length === 0) return [];

  const displayFields = [
    "Tanggal_uji", "Iluminasi", "Kolimasi_deltaX", "Kolimasi_deltaY",
    "Akurasi_kV", "Akurasi_waktu", "Linearitas", "Reproduksibilitas",
    "HVL", "HVL_80", "Kebocoran",
  ];

  const fieldLabels: Record<string, string> = {
    Tanggal_uji: "Date", Iluminasi: "Illumination", Kolimasi_deltaX: "Collim. X",
    Kolimasi_deltaY: "Collim. Y", Akurasi_kV: "kV Accuracy", Akurasi_waktu: "Time Accuracy",
    Linearitas: "Linearity", Reproduksibilitas: "Reproducibility", HVL: "HVL",
    HVL_80: "HVL 80%", Kebocoran: "Leakage",
  };

  const availableFields = displayFields.filter((f) => qcData.some((row) => row[f] !== undefined && row[f] !== null));
  const colCount = availableFields.length;
  const colWidth = Math.floor(515 / Math.max(colCount, 1));

  return [
    <View key="table-header" style={styles.tableRow}>
      {availableFields.map((field) => (
        <View key={field} style={[styles.tableHeader, { width: colWidth }]}>
          <Text>{fieldLabels[field] || field}</Text>
        </View>
      ))}
    </View>,
    ...qcData.map((row, ri) => (
      <View key={ri} style={styles.tableRow}>
        {availableFields.map((field) => (
          <View key={field} style={[styles.tableCell, { width: colWidth }]}>
            <Text>{String(row[field] ?? "-")}</Text>
          </View>
        ))}
      </View>
    )),
  ];
}

export default function AIReportPDF({ markdown, qcData, machine, startDate, endDate }: AIReportPDFProps) {
  const aiElements = renderMarkdownToPDFElements(markdown);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>QC Report - AI Generated</Text>
          <Text style={styles.subtitle}>
            Radiography Quality Control Report  |  {startDate} to {endDate}
          </Text>
          {machine && (
            <Text style={styles.machineInfo}>
              {machine.Merk} {machine.Model}  |  Serial: {machine.No_Seri}  |  {machine.jenis_pesawat}
            </Text>
          )}
        </View>

        <View>
          <Text style={styles.sectionTitle}>AI Analysis</Text>
          <Text style={styles.aiBadge}>This section was generated by AI (Gemini 2.0 Flash)</Text>
          {aiElements}
        </View>

        <View>
          <Text style={styles.sectionTitle}>QC Data</Text>
          <View style={styles.table}>
            {buildQCDataTable(qcData)}
          </View>
        </View>

        <Text style={styles.footer}>
          Generated on {new Date().toLocaleDateString("en-CA")}  |  Kendali-Mutu QC System
        </Text>
      </Page>
    </Document>
  );
}
